<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl"?>
<!DOCTYPE mail [
    <!ELEMENT mail (to, from, subject, message)>
    <!ELEMENT to (#PCDATA)>
    <!ELEMENT from (#PCDATA)>
    <!ELEMENT subject (#PCDATA)>
    <!ELEMENT message (#PCDATA)>
]>
<mail>
    <to>Ram</to>
    <from>Sita</from>
    <subject>Hello</subject>
    <message>Abort!! Abort!!</message>
</mail>