=== Abhil-ekh/5th-Sem/WT/5xml/lab7.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="person">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name">
                                <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[A-Za-z ]+" />
                                </xs:restriction>
                                </xs:ssimpleType>
                            </xs:element>
                            <xs:element name="age">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="16" />
                                        <xs:maxInclusive value="18" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="pincode">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[0-9]{4}" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Abhil-ekh/5th-Sem/WT/5xml/lab7.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl"?>
<person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="lab7.xsd">
    <student>
        <name>Joe</name>
        <age>17</age>
        <pincode>1234</pincode>
    </student>
    <student>
        <name>John123</name>
        <age>20</age>
        <pincode>12A4</pincode>
    </student>
</person>
